### ISSUE TITLE
Add support for an animation delay

### ISSUE THREAD

**Issue by TheGeekPharaoh** [DarthMike/SwiftAnimations#12]
I notice that all of the other major animation properties are evaluated -- spring dampening, velocity, duration, etc. -- but not delay.  Any chance of adding a setDefaultAnimationDelay() method and support within the animate(){} closure?

**Comment by DarthMike** [comment]
Hey @sdnakhla sorry for late reply
Yes, will get to it shortly :)

**Comment by DarthMike** [comment]
Added support on 1.1.4 version
